### ISSUE TITLE
Default parameters for female for calculating jitter shimmer and F0 

### ISSUE THREAD

**Issue by shanky100** [drfeinberg/PraatScripts#1]
in the measure pitch function present in "Measure Pitch, HNR, Jitter, Shimmer, and Formants.ipynb" it is mentioned that 

# This is the function to measure source acoustics using default male parameters.

Can you please help to provide the default female parameters for the same?

**Comment by drfeinberg** [comment]
100 and 600 hz

**Comment by shanky100** [comment]
Thank you for the reply. 
Just another question regarding the feature extraction through Praat, what other features I can extract using Praat other than the one mentioned in the ipynb file? If yes, then where I can find the code to extract those features or any reference link.
